version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
      - "/src/*"
    schedule:
      interval: "weekly"
    groups:
      all-nuget-updates:
        patterns:
          - "*"
